"""
Content Agent

Responsible for writing social media drafts based on a strategic plan
using the Llama 3 model via the local Ollama API.
"""
from typing import Dict, Any, Optional
from ai.ollama_client import generate

def generate_content(strategy: str, business_profile: Dict[str, Any]) -> Optional[str]:
    """
    Generates social media content drafts based on the provided strategy and business profile.
    
    Args:
        strategy: The strategic plan generated by the Strategy Agent.
        business_profile: A dictionary containing brand information.
        
    Returns:
        The generated content text string, or None if the generation fails.
    """
    prompt = f"""You are an expert social media content creator.

Business Profile:
{business_profile}

Strategy Plan:
{strategy}

Generate the following content based on the strategy:

1 LinkedIn post
1 Facebook post
1 YouTube Short script
Include relevant hashtags.
"""

    content = generate(prompt, model="llama3")

    return content
